### ISSUE TITLE
why we need define storage-provisioner on persistentVolumeClaim

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/ods-core#204]
**Describe the Question**

I want to discuss why the storage-provisioner has to be configurable, as defined in [pvc.yml](https://github.com/opendevstack/ods-core/blob/master/nexus/ocp-config/pvc.yml):

```
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: ${STORAGE_CLASS_DATA}
      volume.beta.kubernetes.io/storage-provisioner: ${STORAGE_PROVISIONER}
```

The provisioner can be defined in the storage-class, that is referenced by the annotation `volume.beta.kubernetes.io/storage-class`

For example, a storage-class for local-storage can be defined: 

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
```
