### ISSUE TITLE
Get rid of all route related config settings 

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-core#517]
**Describe the bug**
Why do we need People to set route hosts/URLs?

As we seed the resources.. we can always find the host/url combos thru oc get.

**Comment by michaelsauter** [comment]
You want to remove the config from the `configuration-sample/ods-core.env.sample` file so that people do not need to configure it?

That would not easily be possible as those values are used as parameters for the templates. When doing template processing, we do not run `oc get / oc create`.

Or did you mean something else?

**Comment by clemensutschig** [comment]
Well .. i assume that removing the part from the Route Templates would
force ocp to generate?

Michael Sauter <notifications@github.com> schrieb am Mo., 4. Mai 2020,
08:49:

**Comment by michaelsauter** [comment]
Many places also use the URL outside of the `Route` resource, e.g. as environment variable in the Jenkins pod. All those places would need a "preprocessing step" to fetch the URL. I am not sure this is worth the effort/complexity. I'm going to label this as a question and will remove it from the 3.0 release for now.

**Comment by michaelsauter** [comment]
As a note to posterity: sometimes the services might run outside of OpenShift (e.g. one can host Nexus elsewhere). In that case, users need to define where Nexus is, and that information cannot be automatically collected.

I'm leaving this open as it is something to think about, but might not be resolved anytime soon.

**Comment by clemensutschig** [comment]
ok - I tried it finally
```
apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: test-route
    name: test-route
  spec:
    port:
      targetPort: 9000-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: sonarqube
      weight: 100
    wildcardPolicy: None
```
```
tailor apply
```
```
utschig@WKS0000627058 MINGW64 /c/Temp/routet
$ oc get route/test-route -ojsonpath='{.spec.host}'
test-route-odsst-cd.*somehost* 
``` 
so this works super nicely - and would allow us to go completely route-less in the config ...
