### ISSUE TITLE
ds-rshiny test runs into timeout

### ISSUE THREAD

**Issue by georgfedermann** [opendevstack/ods-core#791]
**Describe the bug**
the r-shiny quickstarter tests run into a timeout after some other quickstarters tests have already completed successfully.

**To Reproduce**
1. Run quickstarter tests in ODS box
2. See error

**Expected behavior**
The test should pass.

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack latest master

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
    amazon-ebs: Starting pipeline prov-ds-rshiny-opendevstack
    amazon-ebs: Pipeline: prov-ds-rshiny-opendevstack, response: {"kind":"Build","apiVersion":"build.openshift.io/v1","metadata":{"name":"prov-ds-rshiny-opendevstack-master-1","namespace":"unitt-cd","selfLink":"/apis/build.openshift.io/v1/namespaces/unitt-cd/buildconfigs/prov-ds-rshiny-opendevstack-master-1/instantiate","uid":"ca1414c6-e890-11ea-b8e6-0a7c436fc771","resourceVersion":"35377","creationTimestamp":"2020-08-27T18:11:55Z","labels":{"buildconfig":"prov-ds-rshiny-opendevstack-master","openshift.io/build-config.name":"prov-ds-rshiny-opendevstack-master","openshift.io/build.start-policy":"Serial"},"annotations":{"openshift.io/build-config.name":"prov-ds-rshiny-opendevstack-master","openshift.io/build.number":"1"},"ownerReferences":[{"apiVersion":"build.openshift.io/v1","kind":"BuildConfig","name":"prov-ds-rshiny-opendevstack-master","uid":"ca0fee50-e890-11ea-b8e6-0a7c436fc771","controller":true}]},"spec":{"serviceAccount":"builder","source":{"type":"Git","git":{"uri":"http://bitbucket.odsbox.lan:7990/scm/opendevstack/ods-quickstarters.git","ref":"master"},"sourceSecret":{"name":"cd-user-with-password"}},"strategy":{"type":"JenkinsPipeline","jenkinsPipelineStrategy":{"jenkinsfilePath":"ds-rshiny/Jenkinsfile","env":[{"name":"ODS_NAMESPACE","value":"ods"},{"name":"ODS_GIT_REF","value":"master"},{"name":"ODS_IMAGE_TAG","value":"latest"},{"name":"PROJECT_ID","value":"unitt"},{"name":"COMPONENT_ID","value":"rshiny"},{"name":"GIT_URL_HTTP","value":"http://bitbucket.odsbox.lan:7990/scm/unitt/unitt-rshiny.git"}]}},"output":{},"resources":{},"postCommit":{},"nodeSelector":{},"triggeredBy":[{"message":"Generic WebHook","genericWebHook":{"secret":"########"}}]},"status":{"phase":"New","config":{"kind":"BuildConfig","namespace":"unitt-cd","name":"prov-ds-rshiny-opendevstack-master"},"output":{}}}
    amazon-ebs: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Success","message":"no git information found in payload, ignoring and continuing with build","code":200}
    amazon-ebs:
    amazon-ebs: Pipeline: prov-ds-rshiny-opendevstack, build name from response: prov-ds-rshiny-opendevstack-master-1
    amazon-ebs: Verifying Jenkins stages of prov-ds-rshiny-opendevstack-master-1 ...
    amazon-ebs: Getting stages for build: prov-ds-rshiny-opendevstack-master-1 in project: unitt-cd
    amazon-ebs: Waiting for build to complete: prov-ds-rshiny-opendevstack-master-1. Current status: Running
    amazon-ebs: panic: test timed out after 1h0m0s
```

**Additional context**
If additional context is required we can run a manual build and conserve the EC2 instance to investigate the state of Jenkins build pipelines etc.
